repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: 'cargo check'
        language: system
        entry: cargo check
        files: 'src/'
        pass_filenames: false

      - id: rustfmt
        name: 'rustfmt'
        language: system
        entry: cargo fmt
        files: 'src/'
        pass_filenames: false
